name: upgrader
description: Flutter package for prompting users to upgrade when there is a
  newer version of the app in the store.
version: 6.2.0
homepage: https://github.com/larryaasen/upgrader

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  device_info_plus: ^9.1.2
  flutter:
    sdk: flutter
  html: ^0.15.1
  http: ^1.2.0
  os_detect: ^2.0.1
  package_info_plus: ^5.0.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  version: ^3.0.2
  xml: ^6.1.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

  # From Dart Team: Mock library for Dart inspired by Mockito.
  mockito: ^5.3.2

flutter: null
